services:
  frontend:
    build: ./frontend
    ports:
      - "8080:80"
    container_name: mon_agence_frontend
    volumes:
      - ./frontend:/usr/local/apache2/htdocs/

  backend:
    build: ./backend
    container_name: mon_agence_backend
    volumes:
      - ./backend:/app


  database:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: monagence
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    container_name: mon_agence_db

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    environment:
      PMA_HOST: database
      PMA_USER: user
      PMA_PASSWORD: password
    ports:
      - "8081:80"
